
export enum GroupTypes {
    GENERAL = 1,
    WEAPONS = 2,
    MEDALS = 3,
    ENEMIES = 4,
    RESERVEDGROUPS = 100,
    LEADERBOARD = 101,
    ACTIVITY = 102,
    UNIQUEWEAPON = 103,
    INTERNAL = 104,
    UNKNOWN = 105
}

export enum PeriodTypes {
    NONE = 0,
    DAILY = 1,
    MONTHLY = 2,
    ALLTIME = 3,
    ACTIVITY = 4
}

export enum ModeTypes {
    NONE = 0,
    STORY = 2,
    STRIKE = 3,
    RAID = 4,
    ALLPVP = 5,
    PATROL = 6,
    ALLPVE = 7,
    PVPINTRODUCTION = 8,
    THREEVSTHREE = 9,
    CONTROL = 10,
    LOCKDOWN = 11,
    TEAM = 12,
    FREEFORALL = 13,
    TRIALSOFOSIRIS = 14,
    DOUBLES = 15,
    NIGHTFALL = 16,
    HEROIC = 17,
    ALLSTRIKES = 18,
    IRONBANNER = 19,
    ALLARENA = 20,
    ARENA = 21,
    ARENACHALLENGE = 22,
    ELIMINATION = 23,
    RIFT = 24,
    ALLMAYHEM = 25,
    MAYHEMCLASH = 26,
    MAYHEMRUMBLE = 27,
    ZONECONTROL = 28,
    RACING = 29,
    ARENAELDERCHALLENGE = 30,
    SUPREMACY = 31,
    PRIVATEMATCHESALL = 32,
    SUPREMACYRUMBLE = 33,
    SUPREMACYCLASH = 34,
    SUPREMACYINFERNO = 35,
    SUPREMACYMAYHEM = 36
}