import { NewsArticle } from './dashboard-news-article.interface';

export const ARTICLES: NewsArticle[] = [
    {
        articleId: 0,
        articleTitle: "10 Reasons You NEED This Card!",
        articleCategory: "Site News",
        articleBodyPreview: "Article Text Preview like => Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do tempor incididunt ut labore et dolore magna aliqua.",
        articleBody: "<p>Full Article Text like => Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada lacus ut leo venenatis efficitur. Vestibulum sollicitudin porta ligula, sagittis dapibus arcu sollicitudin a. Morbi dapibus volutpat metus quis gravida. Vestibulum dictum est ut ex dignissim, non aliquam arcu pellentesque. Aliquam pharetra tincidunt sollicitudin. Nunc iaculis dolor a urna venenatis finibus. Nam viverra semper nulla et euismod. Aliquam volutpat magna vel interdum lobortis. Sed ullamcorper faucibus lectus sed aliquet. Suspendisse at ex ultricies, ullamcorper augue auctor, pretium risus.</p><p>Duis non laoreet urna, ut semper felis. Nullam et congue ex, a elementum orci. Donec quis diam vestibulum, vestibulum nisl et, vehicula felis. Mauris sit amet rutrum purus, at ultrices nisi. Suspendisse quis nulla malesuada, fringilla enim at, tincidunt mi. Integer et aliquet nisi. Phasellus placerat nibh ac convallis tincidunt. In hac habitasse platea dictumst. Morbi mollis, erat at congue tincidunt, sem sem dapibus leo, nec convallis ex eros eu erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam congue gravida lorem, a mollis tellus efficitur non. Nullam a mauris imperdiet tortor condimentum aliquam a sodales mauris. Phasellus leo libero, semper eget ullamcorper facilisis, ultricies ut sem. Pellentesque ut tincidunt sapien, quis sagittis urna. Duis et facilisis lacus, vel consequat justo.</p>"
    },
    {
        articleId: 1,
        articleTitle: "OMG! Dashboard News!!!",
        articleCategory: "Card Update",
        articleBodyPreview: "Article Text Preview like => Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do tempor incididunt ut labore et dolore magna aliqua.",
        articleBody: "<p>Full Article Text like => Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada lacus ut leo venenatis efficitur. Vestibulum sollicitudin porta ligula, sagittis dapibus arcu sollicitudin a. Morbi dapibus volutpat metus quis gravida. Vestibulum dictum est ut ex dignissim, non aliquam arcu pellentesque. Aliquam pharetra tincidunt sollicitudin. Nunc iaculis dolor a urna venenatis finibus. Nam viverra semper nulla et euismod. Aliquam volutpat magna vel interdum lobortis. Sed ullamcorper faucibus lectus sed aliquet. Suspendisse at ex ultricies, ullamcorper augue auctor, pretium risus.</p><p>Duis non laoreet urna, ut semper felis. Nullam et congue ex, a elementum orci. Donec quis diam vestibulum, vestibulum nisl et, vehicula felis. Mauris sit amet rutrum purus, at ultrices nisi. Suspendisse quis nulla malesuada, fringilla enim at, tincidunt mi. Integer et aliquet nisi. Phasellus placerat nibh ac convallis tincidunt. In hac habitasse platea dictumst. Morbi mollis, erat at congue tincidunt, sem sem dapibus leo, nec convallis ex eros eu erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam congue gravida lorem, a mollis tellus efficitur non. Nullam a mauris imperdiet tortor condimentum aliquam a sodales mauris. Phasellus leo libero, semper eget ullamcorper facilisis, ultricies ut sem. Pellentesque ut tincidunt sapien, quis sagittis urna. Duis et facilisis lacus, vel consequat justo.</p>"
    },
    {
        articleId: 2,
        articleTitle: "Why Are Software Developers So Sexy?",
        articleCategory: "New Feature",
        articleBodyPreview: "Article Text Preview like => Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do tempor incididunt ut labore et dolore magna aliqua.",
        articleBody: "<p>Full Article Text like => Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada lacus ut leo venenatis efficitur. Vestibulum sollicitudin porta ligula, sagittis dapibus arcu sollicitudin a. Morbi dapibus volutpat metus quis gravida. Vestibulum dictum est ut ex dignissim, non aliquam arcu pellentesque. Aliquam pharetra tincidunt sollicitudin. Nunc iaculis dolor a urna venenatis finibus. Nam viverra semper nulla et euismod. Aliquam volutpat magna vel interdum lobortis. Sed ullamcorper faucibus lectus sed aliquet. Suspendisse at ex ultricies, ullamcorper augue auctor, pretium risus.</p><p>Duis non laoreet urna, ut semper felis. Nullam et congue ex, a elementum orci. Donec quis diam vestibulum, vestibulum nisl et, vehicula felis. Mauris sit amet rutrum purus, at ultrices nisi. Suspendisse quis nulla malesuada, fringilla enim at, tincidunt mi. Integer et aliquet nisi. Phasellus placerat nibh ac convallis tincidunt. In hac habitasse platea dictumst. Morbi mollis, erat at congue tincidunt, sem sem dapibus leo, nec convallis ex eros eu erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam congue gravida lorem, a mollis tellus efficitur non. Nullam a mauris imperdiet tortor condimentum aliquam a sodales mauris. Phasellus leo libero, semper eget ullamcorper facilisis, ultricies ut sem. Pellentesque ut tincidunt sapien, quis sagittis urna. Duis et facilisis lacus, vel consequat justo.</p>"
    },
    {
        articleId: 3,
        articleTitle: "Lose 40lbs By Using This Card!",
        articleCategory: "Card Update",
        articleBodyPreview: "Article Text Preview like => Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do tempor incididunt ut labore et dolore magna aliqua.",
        articleBody: "<p>Full Article Text like => Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada lacus ut leo venenatis efficitur. Vestibulum sollicitudin porta ligula, sagittis dapibus arcu sollicitudin a. Morbi dapibus volutpat metus quis gravida. Vestibulum dictum est ut ex dignissim, non aliquam arcu pellentesque. Aliquam pharetra tincidunt sollicitudin. Nunc iaculis dolor a urna venenatis finibus. Nam viverra semper nulla et euismod. Aliquam volutpat magna vel interdum lobortis. Sed ullamcorper faucibus lectus sed aliquet. Suspendisse at ex ultricies, ullamcorper augue auctor, pretium risus.</p><p>Duis non laoreet urna, ut semper felis. Nullam et congue ex, a elementum orci. Donec quis diam vestibulum, vestibulum nisl et, vehicula felis. Mauris sit amet rutrum purus, at ultrices nisi. Suspendisse quis nulla malesuada, fringilla enim at, tincidunt mi. Integer et aliquet nisi. Phasellus placerat nibh ac convallis tincidunt. In hac habitasse platea dictumst. Morbi mollis, erat at congue tincidunt, sem sem dapibus leo, nec convallis ex eros eu erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam congue gravida lorem, a mollis tellus efficitur non. Nullam a mauris imperdiet tortor condimentum aliquam a sodales mauris. Phasellus leo libero, semper eget ullamcorper facilisis, ultricies ut sem. Pellentesque ut tincidunt sapien, quis sagittis urna. Duis et facilisis lacus, vel consequat justo.</p>"
    }
];